apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kayenta-demo
  namespace: poc
spec:
  replicas: 5
  revisionHistoryLimit: 5
  rollbackWindow: {}
  selector:
    matchLabels:
      app: kayenta-demo
  strategy:
    canary:
      canaryMetadata:
        annotations:
          role: canary
        labels:
          role: canary
      stableMetadata:
        annotations:
          role: stable
        labels:
          role: stable
      steps:
      - pause:
          duration: 1s
      - experiment:
          analyses:
          - args:
            - name: stable-hash
              valueFrom:
                podTemplateHashValue: Stable
            - name: latest-hash
              valueFrom:
                podTemplateHashValue: Latest
            - name: baseline-hash
              value: '{{ templates.baseline.podTemplateHash }}'
            - name: canary-hash
              value: '{{ templates.canary.podTemplateHash }}'
            - name: start-time
              value: '{{ experiment.availableAt }}'
            - name: end-time
              value: '{{ experiment.finishedAt }}'
            name: mann-whitney
            requiredForCompletion: true
            templateName: mann-whitney
          duration: 30s
          templates:
          - metadata: {}
            name: baseline
            specRef: stable
          - metadata: {}
            name: canary
            specRef: canary
      - pause: {}
  template:
    metadata:
      labels:
        app: kayenta-demo
    spec:
      containers:
      - image: diegofranca886/kayenta-poc:2.4
        imagePullPolicy: Always
        name: kayenta-demo
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: mann-whitney
  namespace: poc
spec:
  args:
  - name: stable-hash
  - name: latest-hash
  - name: baseline-hash
  - name: canary-hash
  - name: start-time
  - name: end-time
  metrics:
  - count: 2
    failureLimit: 1
    interval: 30s
    name: mann-whitney
    provider:
      kayenta:
        address: http://kayenta.h8i-system:8090
        application: kayenta-demo
        canaryConfigName: kayenta-demo-config
        configurationAccountName: canary-storage
        metricsAccountName: canary-prometheus
        scopes:
        - controlScope:
            end: '{{args.end-time}}'
            region: none
            scope: '{{args.latest-hash}}.+baseline.+'
            start: '{{args.start-time}}'
            step: 1
          experimentScope:
            end: '{{args.end-time}}'
            region: none
            scope: '{{args.latest-hash}}.+canary.+'
            start: '{{args.start-time}}'
            step: 1
          name: default
        storageAccountName: canary-storage
        threshold:
          marginal: 70
          pass: 80

---

apiVersion: v1
kind: Service
metadata:
  name: kayenta-demo
  namespace: poc
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: http
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: kayenta-demo
  sessionAffinity: None
  type: ClusterIP
