apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: mann-whitney
  namespace: poc
spec:

  # List of arguments to the template.
  args:
  - name: stable-hash
  - name: latest-hash
  - name: baseline-hash
  - name: canary-hash
  - name: start-time
  - name: end-time

  # List of metrics to query as part of an analysis run
  metrics:
  - name: mann-whitney

    # Defines a metric in which to perform analysis on.
    # Defaults to 0.
    count: 1

    # Maximum number of times the measurement is allowed to fail.
    # Defaults to 0.
    failureLimit: 0

    # The maximum number of times the measurement is allowed to measure inconclusive.
    # Defaults to 0.
    inconclusiveLimit: 0

    # The maximum number of times the measurement is allowed to error in succession.
    # Defaults to 4.
    consecutiveErrorLimit: 0

    # Defines an interval string between each measurement.
    interval: 30s

    # How long the AnalysisRun should wait before starting this metric.
    # Defaults to 0s.
    initialDelay: 30s

    # Provider configuration to the external system to use to verify the analysis.
    provider:
      kayenta:
        address: http://kayenta.h8i-system:8090
        application: kayenta-demo
        canaryConfigName: kayenta-demo-config
        configurationAccountName: canary-storage
        metricsAccountName: canary-prometheus
        scopes:
        - controlScope:
            end: '{{ args.end-time }}'
            region: none
            scope: '{{ args.latest-hash }}.+baseline.+'
            start: '{{ args.start-time }}'
            step: 1
          experimentScope:
            end: '{{ args.end-time }}'
            region: none
            scope: '{{ args.latest-hash }}.+canary.+'
            start: '{{ args.start-time }}'
            step: 1
          name: default
        storageAccountName: canary-storage
        threshold:
          marginal: 70
          pass: 80
